#server:
#  port: 8002
#spring:
#  application:
#    name: product
#
#eureka:
#  client:
#    instance:
#        prefer-ip-address: true
#    service-url:
#          defaultZone: http://localhost:8000/eureka
